# Generated by Django 3.2 on 2021-04-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='output',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
